src/formatAutocompleteSuggestion.js, src/formatInputValue.js, src/places.scss
Current hint look (can be changed):
=> fix(autocomplete): show the corresponding hint

package.json
=> chore(deps): upgrade to autocomplete.js 0.19.0 to fix the mouseleave events

src/formatHit.js, src/places.js
With the previous code, the `query` attribute was set to the input value AFTER it has been updated.
=> fix(query): the `query` attribute should reflect the original query

docs/source/javascripts/index.js, docs/source/partials/documentation.md.erb, docs/source/partials/hero.html.haml, docs/source/stylesheets/components/_code-highlight.scss, docs/source/stylesheets/components/_documentation.scss, src/places.js
You can now access `originalAlgoliaResponse` in all event data.
Documentation updated.
Homepage example updated to include the `processingTimeMS`
=> feat(rawAnswer): add rawAnswer event data

autocompleteDataset.js, docs/config.rb, docs/source/javascripts/activateClipboard.js, docs/source/javascripts/docsearch.js, docs/source/javascripts/index.js, docs/source/partials/documentation.md.erb, docs/source/partials/examples/_autocomplete_dataset.html.erb, docs/source/partials/examples/_city_search.html.erb, docs/source/partials/examples/_complete_form.html.erb, docs/source/partials/examples/_country_search.html.erb, docs/source/partials/examples/_index.md.erb, docs/source/partials/examples/_simple_input.html.erb, docs/source/partials/examples/_templates.html.erb, docs/source/partials/rest.md.erb, docs/source/stylesheets/site.css.scss, package.json, src/createAutocompleteDataset.js, src/createAutocompleteSource.js, src/defaultTemplates.js, src/formatDropdownValue.js, src/formatHit.js, src/places.js, src/places.scss, webpack.config.babel.js
This PR adds a new autocomplete.js dataset for places. Making it very easy to mix any autocomplete.js results with places.
cc @seafoox :)
+ documentation
+ small fixes
+ no need for CSS nesting, also solves styling the dataset
+ stopped using custom code to not send api keys using JS client
BREAKING CHANGES:
- templates.inputValue => templates.value
- templates.dropdownSuggestion => templates.suggestion
Preview:
=> feat(autocomplete.js): create a reusable places autocomplete.js dataset

docs/source/partials/documentation.md.erb, docs/source/partials/rest.md.erb, docs/source/stylesheets/components/_documentation.scss, docs/source/stylesheets/components/_fonts.scss
- document query strategy
- include GeoNames as part of the data source
- use the new syntax instead of the legacy `params` parameter
=> Here & there documentation improvments

docs/source/partials/documentation.md.erb, docs/source/partials/examples/_complete_form.html.erb, docs/source/partials/examples/_index.md.erb, docs/source/partials/examples/_map.html.erb, docs/source/partials/examples/_map_paris.html.erb, docs/source/partials/examples/_simple_input.html.erb, src/places.js
This PR provides some improvements to the documentation:
- all types now are in bold
- suggestions is now of type Array<Suggestion> to make the array more explicit
- fix the link to the suggestion object reference
This PR also adds a new event `clear` that is triggered when the input field is cleared either when emptying manually or when it is the clear button is hit.
=> Fix doc and add clear event

docs/source/stylesheets/components/docsearch/_docsearch.scss
Just changing the color of the input when focused. 
From : 
To :
=> fix(website): Change docsearch input color on active

src/places.scss
By default the style seems broken which can be frustrating for new users
who want to quick test the library. I wouldn't have made changes if we
didn't already provided styles for some elements.
Fixes #181
=> Fix: default style should be harmonious

docs/source/partials/documentation.md.erb, src/createAutocompleteSource.js
This is required to override the `hosts` array for dev/test purpose for instance.
Happy to have your POV @vvo
=> feat(clientOptions): ability to set REST API client options

docs/source/bootstrap.html.erb, docs/source/partials/documentation.md.erb, src/places.js
This could be useful to set the debug flag to `true` without relying on
process.env.NODE_ENV.
=> feat(autocompleteOptions): expose the autocompleteOptions

docs/config.rb, docs/source/documentation.html.md.erb, docs/source/examples.html.md.erb, docs/source/partials/examples/_instantsearch.html.erb, instantsearchWidget.js, scripts/build.sh, src/instantsearch/widget.js, webpack.config.babel.js
This PR provides an instantsearch.js widget. It adds:
- a new build for the widget so that it can imported by itself
- a documentation entry
- a sample in advanced that couples places.js with google maps
=> feat(instantsearch): Provide an instantsearch.js widget for places

docs/config.rb, docs/source/javascripts/support.js, docs/source/partials/navigation.html.haml, docs/source/support.html.md
This is a proposal on the support part. I do like when Support is easily reachable.
I think every community project should provide this support menu entry to be transparent on where can you get support (github, stackoverflow, email, ..).
There's some custom code to link to a google form with prefilled values for IP address and geolocation.
It handles failures where any of those values is not available and provide fallbacks (we ask the user to go on myip.. etc)
=> docs(support): add support menu entry

docs/source/partials/examples/_instantsearch.html.erb, docs/source/partials/examples/_map.html.erb, docs/source/partials/examples/_map_paris.html.erb
Practical to be able to scroll over the maps. Not cool as it kinda kill
any interactions with google maps instantsearch sample. Not option is
available in instantsearch-googlemaps widget to achieve a middle ground
:(
Do we want that or not?
=> docs(samples): remove pointer events on maps

src/places.js
Warn when:
- container provided with multiple DOM elements
- container not an input
I don't think we need to support multiple DOM elements linked to a single instance of autocomplete.js, this looks like a edge case that is easily solvable user side (instantiate twice).
As for the underlying bug request (#229), it looks like the user do want to have multiple instances since those are different input purposes.
=> fix(errors): precise error messages on some bad usage

src/createAutocompleteSource.js
Authenticated requests would fail because of the two credentials being inverted.
=> fix(initialization): Swap appId and apiKey

docs/source/documentation.html.md.erb, src/createAutocompleteDataset.js, src/createAutocompleteSource.js, src/places.js
When you reach the rate limit:
if you are listening to the limit event: you will receive that event with {message}
if you are not listening to the limit event, we will console.log(message)
message being:
Algolia Places: Current rate limit reached.
Sign up for a free 100,000 queries/month account at
https://www.algolia.com/users/sign_up/places.
Or upgrade your 100,000 queries/month plan by contacting us:
https://community.algolia.com/places/contact.html.
What do you think?
=> fix(limit): add `limit` and `error` events

src/formatHit.js
=> fix(formatHit): fixed npe, not all hits have a country

docs/source/stylesheets/vendors/_normalize.scss
**Summary**
fixes #389
Same reason as why the icon is hidden on Safari and Chrome
**Result**
I don't have a screenshot since I didn't open a VM, but I'm pretty sure that this will work
sources: 
* https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear
* https://msdn.microsoft.com/en-us/library/windows/apps/hh465740.aspx
=> fix(appearance) don't show clear button on IE11

src/places.css
**Summary**
Hide the browser native input type search decoration.
I'm not sure why this wasn't already the case, but we probably never noticed it because it was in our normalise css.
cc @lukyvj @shipow
fixes #389 for real now
**Result**
No browser clear button will be visible.
=> fix(layout) hide the browser clear buttons

CONTRIBUTING.md
Link for conventional changelog is giving 404. Updating it to the correct one (if I'm not mistaken...)
=> Fix link in Contributing.md

docs/source/documentation.html.md.erb
This adds a code example on how to use initPlaces() with the PHP API
Client to do a Places call. I think it only works with registered
account, I could not make it work without credentials.
=> docs(backend): Add PHP backend example

docs/source/javascripts/index.js
Right now, the [demo](https://community.algolia.com/places/) is restricting results in a bbox (~Europe) for no reason.
=> fix(demo): remove bbox demo search

src/places.css
The native appearance of the searchbar on Safari will stay 11px, while if you do `-webkit-appearance: none` it will grow appropriately
before|after
---|---
https://codepen.io/Haroenv/pen/mMVOPP
This bubbles down to default implementations like https://🌚🌞.ws too
=> fix(css): override the appearance of the input

docs/source/partials/examples/_autocomplete_dataset.html.erb
**Summary**
Fixes Autocomplete example bug described here https://github.com/algolia/places/issues/427#issuecomment-325460194
**Result**
When rentalDataset gets selected or autocompleted, suggestion is correctly now passed to event handler.
fixes #427
=> docs(autocomplete): fixing example to correctly return suggestion from rental set

docs/source/contact.html.haml
SFDC doesn't sync well with non-english names hence potential contacts loss.
=> fix(contact): force language to be English to avoid contact misses

docs/source/documentation.html.md.erb, docs/source/rest.html.md.erb
I found three small typos in the docs, and here's a fix!
=> fix(docs) - Fixed latitude/longitude typos

src/places.js
**Summary**
Fixes #454 
places directly used autocomplete's `setVal` which caused issue when the user cleared the input field right after where no clear events would be emitted.
It now updates `previousQuery` to the value passed to `setVal`.
=> fix(events): ensure clear event is emitted after setVal is called

package.json, src/instantsearch/widget.js, src/instantsearch/widget.test.js, yarn.lock
**Summary**
When the widget InstantSearch Places set the position, it should clear the parameters who take predescence on it (ex: `insideBoudingBox`). Means that when we use the widget with a map, the current position of the map will be updated from Places position instead of keeping the current bounding box.
=> feat(InstantSearchWidget): clear the boundingBox when perform a search

docs/source/documentation.html.md.erb, src/formatHit.js, src/formatHit.test.js
**Summary**
This PR exposes the suburb field that is available from the API.
In some countries like Australia, the city field is not sufficient to get an accurate address and the suburb field should be used.
For instance, `1 perth old road` would yield `Perth, Western Australia, Australia`, while locals would expect either `Bassendean, Western Australia, Australia` or `Bassendean, Perth, Western Australia, Australia`.
This PR fixes #337.
**Note:**
This PR does not modify the `formatDropdownValue` or `formatInputValue`, it only exposes the `suburb` field in `suggestion`. formatting using the suburb field is left to the implementor.
**Result**
http://plnkr.co/edit/suBWvwZGtUhMM4C5qN8J?p=preview
Try with `1 perth old road` for example.
=> feat(suggestion): expose suburb field from API in suggestion

src/places.css
**Summary**
Add box-sizing: border-box to avoid input field override parent 100% width. Solves #472
=> fix(css): add border-box to .ap-input (#472)

src/places.js, src/places.test.js
Add aria-label attributes to be compliance with the accessibility standard and make the autocomplete form render correctly on screen readers.
Affected buttons is:
* clear button
* focus button
Closes https://github.com/algolia/places/issues/470
**Summary**
**Result**
=> feat(autocomplete): add aria-label to buttons

docs/source/contact.html.haml, docs/source/partials/examples/_country_search.html.erb
^ Flag images are missing. The URL apparently doesn't exist anymore.
=> Fix missing flags

src/instantsearch/__snapshots__/widget.test.js.snap, src/instantsearch/widget.js, src/instantsearch/widget.test.js
**Summary**
When using the Places Widget in coordination with other geolocation widget such as the Geosearch, there can be a conflict between the `aroundLatLngViaIP:true` field and the `aroundLatLng` set by Places.
**Result**
`aroundLatLngViaIP` is set to `false` when a user selects a geolocation through places. It is restored to its initial value on clear.
=> fix(viaIP-conflict): disable aroundLatLngViaIP when setting location

docs/config.rb, docs/source/examples.html.md.erb, docs/source/partials/examples/_instantsearch.html.erb
**Summary**
This PR updates the InstantSearch example to use the built-in GeoSearch widget. Note that the examples doesn't work (yet). We should merge the PR #554 before this one. Changes:
- remove the legacy lib script
- update InstantSearch to 2.10.1 (and usage)
- add an API Key for the Google Maps (it removes the overlay)
**Before**
**After**
=> docs: update InstantSearch example

docs/source/documentation.html.md.erb
**Summary**
Adds a Security section that describes the two common patterns to restrict API Key usage (restricted API Keys and secured API Keys).
This will help direct new users to the correct resources when dealing with securing their places API Keys.
**Result**
=> doc(security): Add security section in documenation

docs/source/javascripts/documentation-layout.js, docs/source/stylesheets/components/_clipboard.scss, docs/source/stylesheets/components/_code-highlight.scss
**Summary**
This PR fixes a bug where clipboardJS was applied to the wrong selector.
Copy to clipboard is now back on code samples, with _very slightly_ fresher styles.
This makes it a lot easier for our users to reuse our examples.
**Result**
Example on the documentation page:
Example on the example page:
=> doc(copy-examples): fix clipboard selectors and code block style

docs/source/api-clients.html.md.erb, docs/source/documentation.html.md.erb, docs/source/index.html.haml, docs/source/partials/navigation.html.haml, docs/source/stylesheets/components/_documentation.scss
**Summary**
Moves the API Clients documentation together with the Rest API documentation and exposes the page in the nav bar.
Moves the autocomplete.js and IS.js subsections of Usage into an Integrations sections in the main documentation page.
**Result**
- API Clients page
- Integrations section in Documentation
=> doc(api-clients): combine rest doc and api clients doc in separate page

docs/source/api-clients.html.md.erb, docs/source/documentation.html.md.erb
**Summary**
- Adds documentation about Places in the mobile clients
- Makes the clients use the pulled credentials
- Fixes the credentials in the documentation page
**Result**
Swift
Android
Documentation
The credentials were manually shortened for security reasons
=> doc(mobile-clients): add documentation about usage of Places in mobile clients

docs/source/documentation.html.md.erb, docs/source/javascripts/index.js, src/formatHit.js, src/formatHit.test.js
**Summary**
This PR exposes the postcodes array in the suggestion object.
It now also returns the best matching postcode as `postcode` when possible.
the postcode field is now also included in the highlight object.
**Result**
- exposes the postcodes field
- updates tests to include postcodes array
- updates the documentation to include section about postcodes
- update landing formatting with new postcodes object (truncated for readability)
=> feat(postcodes): expose postcodes array in suggestions

docs/source/api-clients.html.md.erb, docs/source/documentation.html.md.erb, docs/source/examples.html.md.erb, docs/source/partials/examples/_ranking_info.html.erb, src/createAutocompleteSource.js, src/createAutocompleteSource.test.js
**Summary**
This PR documents how `_rankingInfo` functions in Places, and allows places.js to use getRankingInfo, which was already available through the REST API or the API Clients.
It includes an example about the two special fields that Places injects in `_rankingInfo`.
**Result**
=> feat(ranking-info): expose and explain _rankingInfo

src/createAutocompleteDataset.js, src/createAutocompleteDataset.test.js
**Summary**
The autocomplete instance was caching the first letter query, and does not check for changes in the parameters. This behaviour was buggy and led to having the instance return the same results for single letter queries regardless of configuration change.
E.g: `L` with `type: 'city'` will be cached (returns Toulouse) and changing the type to `country` and typing `L` will return again `Toulouse`.
The JS client already does caching of previous queries so there is no point in having that cache that introduces bugs.
=> fix(caching): disable autocomplete caching

docs/source/documentation.html.md.erb, docs/source/index.html.haml
**Summary**
This PR updates links to point to the new location of some of the documentation content in Algolia Doc after the refresh.
This PR is **low priority** because **no link was broken** with the refresh of the documentation, although some of the current hashes will be incorrect and therefore we will not always direct the visitor to the exact content we were pointing to before.
**Result**
- Fixes 1 already broken link (link to current doc returns 404)
- Improves the links' hashes to point the exact same content as before (or the closest reworked content)
**Methodology**
I grep'ed the documentation looking for the pattern `algolia.com/doc`, and checked every link. If we have any links to the documentation that does not match this pattern, I will have missed them.
I looked for …
=> doc(fix-broken-links): prepare documentation for Algolia doc refresh

package.json, yarn.lock
**Summary**
It seems that our node transpiled version has an issue with the pinned version of @babel/node, which relied on @babel/polyfills#7.0.0 which had a bug where it did not include correctly import its core-js dependency.
To fix this, I reset the lockfile and added `@babel/polyfill` with a non bugged version to fix the issue.
**Result**
Library does not crash when used with `import`.
**Next Steps**
This bug has been present for a while but was not detected because we were not using polyfills until the IE11 release, and therefore we were not hitting that part of the code.
The current ways of validating the build rely on the self contained library which is not compiled through babel-node but by webpack, and uses a correct version of `@babel/polyfills`. Therefore a clear next step is …
=> fix(babel-node): fix a critical bug where missing polyfills were crashing the library

package.json
**Summary**
This PR makes `@babel/polyfill` a main dependency, as the previous fix still failed in some cases.
**Result**
Hopefully, the library is now properly compiled.
=> fix(babel-node): make @babel/polyfill a main dependency

.babelrc, package.json, src/configure/index.js, src/createAutocompleteSource.js, src/instantsearch/widget.js, src/places.js, yarn.lock
**Summary**
The polyfills we introduced to support IE11 created an issue with the usage of `Promise.finally` due to a bug in the way Babel checks for the polyfill usage: https://github.com/babel/babel/issues/8297#issuecomment-403673151
This PR removes `@babel/polyfill` and uses an alternative syntax for Object.assign that is automatically polyfilled by babel #magic
**Result**
Search works and .finally works in Firefox and in IE11
=> fix(promise-polyfill): remove babel-polyfill and let babel do magic

src/formatHit.js, src/formatHit.test.js
closes #750 
**Summary**
It seems that some records return an empty list of postcodes instead of returning no postcode field at all. This caused issue because we assumed that if the `postcode` field was present, then the `_highlightResult` would also be present, which is not true for empty lists.
This PR fixes that by checking for the empty list.
=> fix(empty-postcode-list): fix a bug where an empty postcode list would crash display

autocompleteDataset.js, src/places.js
closes #663 
**Fixes**
- **fix(set-val-icon)**: shows clear icon when calling setVal with non-empty string and pin icon when calling with empty string.
- **fix(raw-loader)**: createAutoCompleteDataset now uses es6 module syntax for css.
=> fix(set-val-icon): show correct icon when calling setVal

src/configure/index.js, src/createAutocompleteSource.js, src/createAutocompleteSource.test.js, src/createReverseGeocodingSource.js, src/createReverseGeocodingSource.test.js, src/errors.js, src/places.js, src/places.test.js
Display a clearer error message when the APP ID is invalid (not a Places app)
=> Invalid credentials

package.json, src/places.test.js, yarn.lock
Setting it to `6.1.0` because `6.2.0` is failing identifying a wrong unused var. See https://github.com/eslint/eslint/issues/12117
=> chore(deps): update eslint to v6

scripts/build.sh
Latest version changed a config param not supported as is anymore cf. https://github.com/mishoo/UglifyJS2/issues/3394
Anyway, it's not important and it's false by default! Will unlock PR #793
=> chore(deps): fix error with latest uglifyjs

docs/source/documentation.html.md.erb
**Summary**
Fixes a broken link that appeared with the redesign of the website. Now points the brand guidelines page.
=> chore(broken-link): fix link to logo with link to branding page

src/places.css, test/cdn-autocomplete-min/index.html, test/cdn-autocomplete/index.html, test/cdn-main-min/index.html, test/cdn-main/index.html, test/cdn-widget-min/index.html, test/cdn-widget/index.html, test/e2e.test.js, test/npm-lib/index.html
**Summary**
This PR makes it so that our e2e tests use an authenticated places app instead of the unauthenticated mode. The api key we use is restricted to community.algolia.com.
This fixes issues where certain tests would fail because the queries were rejected due to having reached the limits.
**Result**
```
yarn test
```
works no matter how many times they are run.
=> fix(rate-limit-ci): Use authenticated places app in E2E tests

.eslintignore, .gitignore, autocompleteDataset.js, babel-css.js, scripts/build.sh, test/cdn-autocomplete/index.html, test/e2e.test.js, test/npm-autocomplete/import.js, test/npm-autocomplete/index.html, test/npm-widget/import.js, test/npm-widget/index.html
Closes #886 
**Summary**
Uses babel transpiler to inliine the css into the autocomplete file.
**Result**
```
npm run build
less dist/autocomplete.js # <- should have a css variable instead of a require
```
I am on vacation, so I'll let you release.
=> fix(autocomplete-css): use babel transpiling for places.css

docs/source/api-clients.html.md.erb
**Summary**
Our code sample for the PHP client was outdated since there was a major release of the PHP client which changed the way to instantiate a places client.
This PR corrects that code and provides a link to the migration guide for people using the php client v1.
=> doc(fix-php-example): use latest syntax for instantiating places client

docs/source/documentation.html.md.erb, src/places.js, test/npm-lib/index.html
closes #860
**Summary**
This PR enables our users to apply arbitrary attributes on the clear and pin buttons, which enables one to override aria-labels if desired, set a tab-index, etc.
This PR also updates the documentation to present that functionality
**Result**
attributes set in accessibility are propagated to the correct button (as shown in `test/npm-lib/index.html`)
=> feat(accessibility): allow modification of attributes on pin and clear buttons

src/places.js, src/places.test.js, test/e2e.test.js, yarn.lock
Closes https://github.com/algolia/places/issues/906
**Summary**
This PR fixes an issue where we called the wrong method on autocomplete, which led to `getVal` always returning `undefined`.
**Result**
Calling `placesInstance.getVal()` now returns the value currently present in the input (see new e2e tests)
**Note:** I also did a yarn upgrade to fix some yarn.lock warnings that were not needed
=> fix(get-val): call autocompleteInstance.val instead ac.autocomplete.getVal

package.json, yarn.lock
**Summary**
`eslint-plugin-jasmine` is a plugin to use to lint files using the jasmine testing library. We have been using jest for a while now (which uses jasmine underneath), and the linting rules relevant for jasmine are already covered by the `eslint-plugin-jest` in our dev deps.
=> chore(deps): remove eslint-plugin-jasmine from devDeps

package.json, yarn.lock
Closes #939
**Summary**
This PR updates the version of algoliasearch and moves algolia-aerial to a dev-deps as it is only used in the docs build, rather than in the library.
=> chore(deps): bump algoliasearch to 3.35.1 and move algolia-aerial to dev deps

.travis.yml
**Summary**
This PR removes the pre_install step of installing yarn (since it's now supported by travis by default).
**Result**
CI should be green and with up-to-date yarn versions.
=> chore(better-ci): remove yarn installation from travis config

test/e2e.test.js
**Summary**
This PR changes the way we count queries that should be run to also include completed queries, to remove certain race conditions where queries could finish before our check for pending requests.
**Result**
CI should be green(er).
=> chore(flaky-e2e-test): improve e2e tests to be less flaky

docs/source/api-clients.html.md.erb, docs/source/documentation.html.md.erb, docs/source/examples.html.md.erb, docs/source/partials/examples/_postcode_search.html.erb, src/configure/index.js
**Summary**
Adds a `postcodeSearch` attribute to places.js and documents it (in documentation and in examples).
Adds documentation for the underlying usage of the REST API `restrictSearchableAttributes` parameter.
=> feat(postcode-search): add postcodeSearch attribute

src/createAutocompleteSource.js, src/createAutocompleteSource.test.js
**Summary**
This PR adds a few tests around the postcodeSearch attribute and fixes a bug where passing `postcodeSearch: true` in the places static fields instead of in `.configure` would be ignored.
**Result**
```sh
yarn test # passes
```
=> test(postcode-search): add test for postcodeSearch

docs/source/api-clients.html.md.erb
**Summary**
The `hitsPerPage` parameter is limited to 20 max, but I couldn't find this mentioned anywhere in the documentation.
=> docs: mention max hitsPerPage

docs/source/documentation.html.md.erb, src/places.js, src/places.test.js
**Summary**
Allow the pin to emit a `locate` event when clicked. This will allow integrating code to determine when a user enables geolocation in the browser and act upon it.
This addresses an issue as discussed in algolia/places#952.
I came across this too as I wanted to use the `places` module in a Facebook Messenger Webview. The pin icon looks like it should geolocate the user so having this as an additional event would allow me to do this without tying it to the `places` implementation.
I chose the name `locate` for the event but I'm happy to change this to a better name if appropriate. I've added a unit test for this but had to refactor the mocking of `createAutocompleteDataset` as it's set up prior to the `places` instance being created before every test. I felt this was appropriate …
=> feat(autocomplete): add locate event when pin is clicked

docs/source/documentation.html.md.erb
closes #1004 
**Summary**
This PR documents the fact that the IS widget is now owned by the InstantSearch repository.
**Result**
=> chore(is-docs): document change of ownership of places IS widget

package.json, yarn.lock
**Summary**
This PR reverts an auto-upgrade of a dependency that made tests flaky.
**Result**
```
yarn test:e2e
```
=> fix(deps): revert auto-upgrade of pending-xhr-puppetteer

docs/source/layouts/landing.erb, docs/source/layouts/layout.erb
**Summary**
This PR adds an html redirect to the `contact.html` page, so that it automatically redirects to `https://www.algolia.com/contactus/` even if clicked from google.
**Result**
N/A
=> doc(contact-form): add html redirect to page

README.md, docs/source/documentation.html.md.erb, docs/source/partials/navigation.html.haml
**Summary**
This PR fixes an orphan link due to the blog maintainers moving the sunset announcement to a new location without redirects.
=> chore(docs): update broken link
