docs/source/partials/marketing.html.erb
I couldn't find why...
Fix #69
=> docs(website): middleman madness removing leading slashes

docs/source/stylesheets/components/_containers.scss, docs/source/stylesheets/components/_navigation.scss, docs/source/stylesheets/vendors/_mixins.scss, docs/source/stylesheets/vendors/_variables.scss
Some fixes added after a discussion with @antoineplu
=> fix(website): hero section reworked

docs/source/documentation.html.haml, docs/source/partials/documentation/documentation.md.erb, docs/source/stylesheets/components/_documentation.scss, src/createHitFormatter.js, src/places.js
=> docs(API): full API doc

docs/source/stylesheets/components/_buttons.scss, docs/source/stylesheets/components/_containers.scss, docs/source/stylesheets/components/_documentation.scss, docs/source/stylesheets/components/_fonts.scss, docs/source/stylesheets/site.css.scss, docs/source/stylesheets/vendors/_svg-animations.scss
In this PR I did a few css cleaning, and I aded a small animation to the heart at the end of the document.
=> chore(website): Clean CSS

docs/source/javascripts/index.js, docs/source/partials/hero.html.haml
This ensure we don't see the original/non-styled input before places.js
has been initialized.
=> docs(website): ensure the hero input is not moving

src/createHitFormatter.js, src/formatAutocompleteSuggestion.js, src/formatInputValue.js
Also, do not use the `administrative` if it has the same value than
`name`.
=> fix(administrative): the `administrative` can be undefined

docs/source/index.html.haml, docs/source/stylesheets/components/_containers.scss
=> docs(homepage): my 2cts pimping the messaging

docs/source/stylesheets/components/_fonts.scss
=> fix(landing): fix title font size on mobile

docs/source/stylesheets/components/_code-highlight.scss
Fix for https://app.asana.com/0/92463766596068/113667270329066
=> fix(examples): fix number line css

src/formatDropdownValue.js, src/formatHit.js, src/formatInputValue.js
For country search for instance. Also, do not display the city if equal
to the locale_name[0].
=> chore(format): city & country may be undefined.

docs/source/partials/documentation.md.erb, docs/source/partials/examples/_city_search.html.erb, docs/source/partials/examples/_complete_form.html.erb, docs/source/partials/examples/_country_search.html.erb, docs/source/partials/examples/_map.html.erb, docs/source/partials/examples/_simple_input.html.erb
=> docs(snippets): ensure we include places.js in all snippets

docs/source/partials/examples/_city_search.html.erb, docs/source/partials/examples/_complete_form.html.erb, docs/source/partials/examples/_country_search.html.erb
**City + Address**: restrict the inputValue to the `name`.
**Country**: display flags
=> docs(examples): make city/country/form examples more relevant

docs/source/javascripts/sidebar.js, docs/source/stylesheets/components/_documentation.scss
=> docs(navigation): ensure the sidebar scrolls while reaching the bottom

docs/source/partials/examples/_city_search.html.erb, docs/source/partials/examples/_complete_form.html.erb, docs/source/partials/examples/_country_search.html.erb, docs/source/partials/examples/_full_styling.html.erb, docs/source/partials/examples/_index.md.erb, docs/source/partials/examples/_input_styling.html.erb, docs/source/partials/examples/_map.html.erb, docs/source/partials/examples/_map_paris.html.erb, docs/source/partials/examples/_simple_input.html.erb, docs/source/partials/examples/_templates.html.erb, docs/source/stylesheets/components/_examples.scss, src/places.js
The first example is still broken, it raises a `Bounds are not valid` error while trying to `fitZoom` -> I don't get it @vvo  :/
=> docs(examples): fixed naming conflicts between the 2 map examples

docs/source/index.html.haml
Some corrections made by @lae25c.
=> style(website): Fixed content typos on main page

docs/config.rb, docs/source/javascripts/rest.js, docs/source/partials/documentation.md.erb, docs/source/partials/rest.md.erb, docs/source/rest.html.haml, docs/source/stylesheets/components/_documentation.scss
=> docs(apis): review the Places.js documentation and bootstrap the REST API one

docs/source/stylesheets/components/_navigation.scss, docs/source/stylesheets/components/docsearch/_searchbox.scss
Small tweaks after @aplu feedbacks.
=> Perfect header navigation

docs/source/partials/examples/_autocomplete_dataset.html.erb
Replaced Products by Vacation Rentals search
=> docs(example): improve the custom data example

docs/source/documentation.html.md.erb, docs/source/javascripts/index.js, src/createAutocompleteSource.js
- add useDeviceLocation option
- add computeQueryParams option
Make useDeviceLocation default on the places website
=> feat(precision): add useDeviceLocation option

docs/source/stylesheets/components/_containers.scss
| From  | To |
| ------------- | ------------- |
| ![](http://puu.sh/ptC29/f9c5337648.png)  | ![](http://puu.sh/ptC3G/3f73a51f03.png)  |
=> fix(website): fix json response, thanks @dzello for the heads up

docs/source/documentation.html.md.erb
Updated the rate limit wording to fit with the current rate-limit implementation.
=> docs(website): Updated the rate limit wording to fit with the current

docs/source/index.html.haml, docs/source/stylesheets/components/_containers.scss
https://www.youtube.com/watch?v=HgzGwKwLmgM
=> docs(show-off): add github button

.gitignore, CONTRIBUTING.md, mocha.opts, package.json, scripts/build.sh, scripts/release.sh, src/__mocks__/algoliasearch/lite.js, src/__mocks__/autocomplete.js.js, src/createAutocompleteDataset.js, src/createAutocompleteDataset.test.js, src/createAutocompleteSource.js, src/createAutocompleteSource.test.js, src/errors.js, src/findCountryCode.test.js, src/findType.test.js, src/formatDropdownValue.js, src/formatDropdownValue.test.js, src/formatHit.test.js, src/formatInputValue.js, src/formatInputValue.test.js, src/instantsearch/widget.test.js, src/places.js, src/places.test.js
This is using Jest as an experiment and a way to have automocking
of modules.
I learned later on that we could achieve the same with
https://github.com/mfncooper/mockery.
=> test(lib): full unit test suite

docs/source/documentation.html.md.erb, src/formatDropdownValue.js, src/formatDropdownValue.test.js, src/formatHit.js, src/formatHit.test.js
Not sure this is the right naming.
=> feat(highlight): add highlited attributes in the suggestion data

docs/source/partials/examples/_city_search.html.erb, docs/source/partials/examples/_country_search.html.erb
City search: make sure the geo don't impact the ranking
Country search: use the simpler `suggestion.highlight` way
=> docs(examples): improved examples

src/formatHit.js, src/formatHit.test.js
=> feat(highlight): get the best matching values instead of the first one

docs/source/documentation.html.md.erb, docs/source/rest.html.md.erb
=> chore(type): ability to filter on the new busStop, trainStation, townhall & airport types

src/createAutocompleteSource.js, src/createAutocompleteSource.test.js
=> fix(createAutocompleteSource): missing hitsPerPage forward

package.json
@vvo would love your inputs about the `peerDependencies`. Worst case, we depend on those libraries as `devDependencies`.
=> chore(autocomplete.js): upgrade to latest stable

docs/source/rest.html.md.erb
Maybe I got this wrong but it it seems the links are messy.
=> update iso on docs

src/createAutocompleteSource.js, src/createAutocompleteSource.test.js
=> fix(codes): lowercase countries and language

docs/source/rest.html.md.erb
=> Add documentation for the getObject endpoint

autocompleteDataset.js
=> fix(IE10): add navigatorLanguage polyfill in autocompleteDataset

README.md
Trying to move users from opening issues to use the GForm
=> docs(repo): add link to the irrelevant results Google form

docs/source/partials/marketing.html.erb
=> Updated Tracking (GTM)

docs/source/documentation.html.md.erb
=> doc(geo): Add insideBoundingBox and insidePolygon

docs/source/documentation.html.md.erb
Document `places.getObject();` See algolia/places#381
=> doc(api): add getObject

docs/source/javascripts/index.js, package.json, src/createAutocompleteSource.js, src/createAutocompleteSource.test.js, yarn.lock
this is only the code, needs documentation
=> feat(geo): add insideBoundingBox insidePolygon

docs/source/documentation.html.md.erb, docs/source/index.html.haml
=> Update databases licenses references

.travis.yml
=> Fix Slack notifications unsecure token

docs/source/pricing.html.md
=> PAYG update pricing page

docs/source/rest.html.md.erb
Some contributions here and there.
=> docs(rest): add page parameter

package.json, scripts/bump-package-version.js, yarn.lock
=> chore(release): drop mversion, buggy on node 10

docs/source/javascripts/index.js
https://github.com/algolia/places/issues/510
=> Fix(display): capturing group not displaying negative lat/lng

docs/source/index.html.haml
**Summary**
This PR adds a sign up CTA on the landing.
**Result**
**Next Steps**
- Add some sign up links in the documentation page
=> feat(cta): add signup CTA on landing

docs/source/documentation.html.md.erb
Update documentation on licenses and policies
=> doc(policy): update policies

docs/source/documentation.html.md.erb
**Summary**
Clarify limitations of the Places library as well as ways to use Places.
**Result**
⚠️ Looking for feedback on what to write exactly in the section.
=> doc(warning-house-level): add what is places section

.babelrc, package.json, yarn.lock
**Summary**
We are relying on `babel-plugin-webpack-loaders` to resolve `.css` and `.svg` imports when building the npm package. However this library is not recommended by its own creator anymore: https://www.npmjs.com/package/babel-plugin-webpack-loaders#important-note
It also has a hard dependency on babel 6 and webpack 2 which causes issue with our renovate PRs for babel 7 and webpack 4.
We should replace it with a babel plugin that has the same behaviour as this plugin for our project and with lower dependencies constraints.
The plugin `babel-plugin-inline-import` does the same thing and does not have a hard dependency on webpack 2.
**Result**
I compared the changes when using the new plugin vs using the old one: (this is only file used for illustration of the difference, but the …
=> chore(babel-text-imports): change babel dependencies for .svg and .css

docs/source/javascripts/sidebar.js, docs/source/stylesheets/components/_sidebar.scss
**Summary**
Modifies the sibebar styling so that it fits a smaller screens
**Result**
=> chore(collapse-doc): change the style for sidebar so that it fits

CHANGELOG.md
**Summary**
Some of the commits we merged into master had semantic commit handles but were unrelated to places.js (they focused on fixing the docs for instance).
This PR removes out of scope changes from the CHANGELOG.md file.
This will improve the quality of the upcoming status page since it includes the latest changes.
=> chore(changelog): remove changes irrelevant to places.js

DATA_REFRESH.md, PIPELINE_CHANGELOG.md
**Summary**
This commit was generated automatically by `rake deploy:website` to reflect the latest pipeline changelog and refresh of the data..
=> chore(pipeline-changelog): update pipeline-changelog

docs/source/support.html.md
**Summary**
This PR adds an how-to about checking if a result is incorrect in OpenStreetMap and also repeats some of the limitations of Places that are not considered as issues.
**Result**
How to:
Places limitations:
=> chore(support-doc): add OSM how to and caveats to the support page

docs/source/api-clients.html.md.erb
**Summary**
removes an invalid page parameter
**Result**
=> chore(remove-page-param): remove invalid parameter

typings.d.ts
Hi, 
This PR aims to add typescript typings to this package.
They are necessaries to use it in typescript projet, and they are really useful even in standard javascript projects, for ide autocompletion and documentation directly in code.
This is a work in progress PR, just to show you the work started, and be sure you would like to add them before spending more time on it.
I've made them ones for personal use, based on your documentation (which is really complete, thanks for that!), and they work really well in my project.
Edit: 
_You could want to add them to a @types/xxx repository. I'll strongly strongly advise against it. Contributing on DefinitelyTyped repository is a mess, you don't own the package, and can't control contributions, so keeping types up to date is more complicated. …
=> chore(typings): Add Typings.

scripts/release.sh, typings.d.ts
**Summary**
This should package the typings within the npm package distribution.
**Result**
=> chore(release-typings): include typings in dist directory

docs/source/contact.html.haml, docs/source/stylesheets/components/_inputs.scss
**Summary**
2 weeks ago a new field was added in Pardot and the contact form that linked to Pardot was not updated to include this new field. This PR fixes that.
**How to test**
```
yarn dev
```
1. go to contact
2. submit info
3. returns a success message
=> chore(broken-contact-form): update Contact form with new field

package.json
**Summary**
This PR makes it so that typescript knows where to look for the typings (see https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)
**Result**
=> fix(typings): include types field in package.json

docs/source/documentation.html.md.erb
Clarify the policy using places.js
=> fix(doc): clarify policy on the Algolia logo

.travis.yml, docs/Gemfile.lock
**Summary**
upgrades bundler version from `1.16.0` to `2.1.2` and travis ruby-version to `2.7.0` which is in line with our `.ruby-version` file.
**Result**
This didn't break the documentation website 🎉
=> chore(deps): upgrade bundler and ruby version

DATA_REFRESH.md
**Summary**
We have released a new update of the planet.
=> chore(data-refresh): Update Release dates

.github/workflows/codeql-analysis.yml
**Summary**
This PR adds codeql to our workflow.
This is an experiment to see what value it can bring to the places codebase.
**Result**
🤷
=> chore(automation): add automated security reviews

docs/source/partials/navigation.html.haml
Redirect contact page to our new page
=> fix(doc): update contact page

.eslintrc.js, package.json, src/createAutocompleteSource.test.js, src/createReverseGeocodingSource.test.js, test/e2e.test.js, yarn.lock
**Summary**
This PR fixes unattended dependency upgrades that needed some minor fixes to pass.
**Result**
```
yarn test
```
=> fix(deps): upgrade json to v10.0.0 and eslint-plugin-jest to v24.1.0

README.md, docs/source/partials/navigation.html.haml, docs/source/stylesheets/components/_navigation.scss
**Summary**
This PR adds a link to the blog post about the sunsetting of Places in the README and in the navigation banner.
**Result**
😢
=> doc(sunset): announce sunset of feature

README.md
used strings to not break the syntax highlighting
**Summary**
**Result**
=> fix: syntax highlighting

docs/source/api-clients.html.md.erb, docs/source/documentation.html.md.erb, docs/source/index.html.haml, docs/source/partials/footer.html.haml, docs/source/pricing.html.md
**Summary**
This PR removes sign up links, as sign ups have been disabled.
=> doc(signup): remove signup links

docs/source/documentation.html.md.erb, docs/source/partials/navigation.html.haml
Fixed the spelling of the blog link from "sunseting" to "sunsetting"
=> Fix blog link spelling

README.md
**Summary**
This PR updates the README to make it even more obvious that the Places is going away.
=> chore(docs): Really insist on the deprecation of service
